version: "3"
services:
  pdo-postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: yoo
      POSTGRES_PASSWORD: yoo
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
