version: "3"
services:
  pdo-mariadb:
    image: mariadb:latest
    ports:
      - "8036:3306"
    restart: always
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    #      MYSQL_ROOT_PASSWORD: yoo
    #      MYSQL_USER: yoo
    #      MYSQL_PASSWORD: yoo
    volumes:
      - ./dbdata:/var/lib/mysql
volumes:
  dbdata:
